sudo: false
language: android
android:
  components:
    - tools
    - build-tools-$BUILD_TOOLS_VERSION
    - platform-tools
    - android-$ANDROID_VERSION
jdk:
  - oraclejdk$JDK_VERSION
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node --version
install:
  - npm install -g ionic cordova
  - npm install
script:
  - bash build_app.sh
branches:
  except:
    - master
notifications:
  email:
    recipients:
      - mdwranger@gmail.com
    on_success: never
    on_failure: always
