sudo: false
language: android
node_js:
  - "6"
jdk:
  - oraclejdk8
before_install:
  - wget https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh -O ~/.nvm/nvm.sh
  - source ~/.nvm/nvm.sh
  - nvm install lts/boron
  - node --version
  - npm install -g ionic
install:
  - npm install
script:
  - ionic platform add android
  - ionic build android
branches:
  except:
    - master
notifications:
  email:
    recipients:
      - mdwranger@gmail.com
    on_success: never
    on_failure: always
