language: node_js
node_js:
  - "6"
install:
  - npm install
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run test
branches:
  except:
    - master
notifications:
  email:
    recipients:
      - mdwranger@gmail.com
    on_success: never
    on_failure: always
