sudo: false
language: android
jdk:
  - oraclejdk8
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 6
  - node --version
install:
  - npm install -g ionic cordova
  - npm install
script:
  - ionic platform add android
  - ionic build android
branches:
  except:
    - master
notifications:
  email:
    recipients:
      - mdwranger@gmail.com
    on_success: never
    on_failure: always
