language: node_js
node_js:
  - "6"
install:
  - npm install
script:
  - npm run test
branches:
  except:
    - master
notifications:
  email:
    recipients:
      - mdwranger@gmail.com
    on_success: never
    on_failure: always
