sudo: false
language: android
node_js:
  - "6"
jdk:
  - oraclejdk8
before_install:
  - npm install -g ionic
install:
  - npm install
script:
  - ionic platform add android
  - ionic build android
branches:
  except:
    - master
notifications:
  email:
    recipients:
      - mdwranger@gmail.com
    on_success: never
    on_failure: always
